### ISSUE TITLE
increase buffer size

### ISSUE THREAD

**Issue by Behrouz-m** [ivanarh/ndcrash#3]
hi. my stack trace is not completed and it trimmed the end of symbol names after 63 chrachter. I think it is rooted here :

https://github.com/ivanarh/ndcrash/blob/8ab2a288a3c918cc1693b0749f8e9f9278e4b9ed/src/ndcrash_dump.c#L102

please consider increasing the buffer size to somthing like 100 or 128.

**Comment by ivanarh** [comment]
>  char proc_cmdline_content[64], proc_comm_content[32];

These 2 arrays are used to store process and thread names respectively.

A limit for function name is here:
https://github.com/ivanarh/ndcrash/blob/1cba2ddbe4b0976175c691ee60d03305be9cdc13/src/ndcrash_private.h#L91

**Comment by ivanarh** [comment]
Would 96 bytes be sufficient for you? I don't want to increase this buffer significantly because this code may be run in a signal handler with a very limited stack size.

**Comment by Behrouz-m** [comment]
yeah that is enough, but 96 bytes or 128 byte are not that much to worry about.

**Comment by Behrouz-m** [comment]
BTW, thanks for this great tool. I was using Crashlytics but it does not work! I've spent 3 weeks to fix it but no result! The support guy said they have a limited stack size in their server which leads to symbol missing!!!

**Comment by ivanarh** [comment]
Done
